### ISSUE TITLE
Return of nested structures of variables not more working since 4.1.0

### ISSUE THREAD

**Issue by klogges5** [camunda-community-hub/camunda-external-task-client-python3#73]
Since Release 4.1.0 we face an issue with returning nested variables.
result until 4.0.0
'docxxx': {'Variable1': 'Test1'}
    
result since 4.1.0:
'doccxxx': Type=Null, Value is empty """

This make the worker unusable for us. 
Regards
Jörg

```python
from camunda.external_task.external_task import ExternalTask, TaskResult
from camunda.external_task.external_task_worker import ExternalTaskWorker

DOCC_IDENTIFIER = "doccxxx"
TOPIC_TO_SUBSCRIBE = f"external_test_variable"
DEFAULT_CLIENT_CONFIG = {
    "maxTasks": 1,
    "lockDuration": 10000,
    "asyncResponseTimeout": 60000,
    "retries": 3,
    "retryTimeout": 5000,
    "sleepSeconds": 30
}
BASE_URL = "http://localhost:8080/engine-rest"


def handle_task(task: ExternalTask) -> TaskResult:
    _business_key = task.get_business_key()
    _topic_name = task.get_topic_name()

    print(f'Execute worker for [Business key: {_business_key}/Topic: {_topic_name}]')

    _result_dict_input = {'Variable1': 'Test1'}
    _result_dict = {DOCC_IDENTIFIER: _result_dict_input}

    """result until 4.0.0
    'docxxx': {'Variable1': 'Test1'}
    
    result since 4.1.0:
    'doccxxx': Type=Null, Value is empty """
    return task.complete(global_variables=_result_dict)


if __name__ == '__main__':
    print(f'Connect to {BASE_URL} to topic: {TOPIC_TO_SUBSCRIBE}')
    ExternalTaskWorker(worker_id=DOCC_IDENTIFIER, base_url=BASE_URL,
                       config=DEFAULT_CLIENT_CONFIG).subscribe(TOPIC_TO_SUBSCRIBE, handle_task)

```

**Comment by klogges5** [comment]
Tested ExternalTask.complete() with postman:
{"workerId": "doccxxx", "variables": {"doccxxx": {"Variable1": "Test1"}}} -> **doesn't work**
{"workerId": "doccxxx", "variables": {"doccxxx": {"value": {"Variable1": "Test1"}}} -> **does work!**

**Comment by klogges5** [comment]
@yogeshrnaik Pull request is submitted

**Comment by yogeshrnaik** [comment]
@klogges5 Thank you. I have merged the PR. I will release 4.3.0 on pypi today EOD.

**Comment by yogeshrnaik** [comment]
Release https://pypi.org/manage/project/camunda-external-task-client-python3/release/4.3.0/

**Comment by mstuebner** [comment]
@yogeshrnaik Beside that we found the solution (klogges5 is a colleague of mine) I'm still curious what the intention of the change in commit #44 was, as I believe that there was an idea behind, that maybe isn't working anymore now?

**Comment by yogeshrnaik** [comment]
@mstuebner 
![image](https://user-images.githubusercontent.com/7280179/155145812-b1ba8e1f-bf36-4ed0-9e4b-7a30c71024cb.png)

Not really sure about impact of this. @jblawatt can you please explain what was the real issue?

**Comment by mstuebner** [comment]
@yogeshrnaik Thanks for your quick response. Why I'm asking is because this module is mission critical to us, so especially breaking changes would be nice to be discussed before. Do you agree?

**Comment by jblawatt** [comment]
@yogeshrnaik @mstuebner 

Please excuse my delayed reply. My vacation prevented me from working ;-) .

The intention of change #44 was that the previous implementation did not allow returning variables of type "Json", "Bytes" or "File". It was always assumed that the value also corresponds to the `value` field, containing primitive types as described here: https://docs.camunda.org/manual/latest/user-guide/process-engine/variables/#supported-variable-values
This behavior reduced the functionality of the Camunda REST API.

Your fix is ok for me because it keeps the functionality I intended.

However, I would also be interested in your background: Returning a Python dictionary as value leads to a "java.util.LinkedHashMap" typed variable. Consuming this value in a subsequent worker, leads to a base64 value of a binary Java Object. Doesn't this make the value almost useless for other (python based) workers?
For the change in #44, I therefore assumed that a dictionary always contains a corresponding formatting. This was obviously wrong.

**Comment by klogges5** [comment]
Hi @jblawatt, 
thanks for your reply. We use the default-serialization-format: application/json and therefore the handling in python worker is not a problem.
