### ISSUE TITLE
Howto handle multiple topics?

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda-community-hub/camunda-external-task-client-python3#79]
Hi @yogeshrnaik,

first thank you for this useful external task worker for Python.

I'm not a python expert. But I need help to build an example.

What would be the best way, to handle two different topics with two different handle methods?

What I have tried so far (and is working) is:

```
def handle_task(task: ExternalTask) -> TaskResult:
    if (task.get_topic_name() == "topicName"):
      return handle_topic1(task)
    elif (task.get_topic_name() == "name2"):
      return handle_topic2(task)
    else:
      logging.error("no handler specified")

def handle_topic1(task: ExternalTask) -> TaskResult:
    logging.info("handle topic %s for task id %s", task.get_topic_name(), task.get_task_id())
    return task.complete({"var1": 1, "var2": "value"}) 

def handle_topic2(task: ExternalTask) -> TaskResult:
    logging.info("handle topic %s for task id %s", task.get_topic_name(), task.get_task_id())
    return task.complete({"var5": 1, "var2": "value20"}) 

ExternalTaskWorker(
      worker_id="pythonWorker", config=default_config).subscribe(
        ["topicName", "name2"], handle_task)
 
```

But I have to put the topic two times in the code: in `subscribe` and `handle_task`.

Is there a better way available to register multiple handlers for multiple topics? How would a python expert approach this challenge?

Thank you and kind regards, Ingo

**Comment by ingorichtsmeier** [comment]
Hi @mstuebner,

thank you for the hints. 

I will provide a pull request to the README page based on your input.

**Comment by flaviocordova** [comment]
the given solution, though works, is really bad. It should be the api's responsibility to handle multiple topics and their associated handlers instead of having a single handler function...

for a future version, it should receive topics and handlers as a dict or being able to chain multiple subscribe callings and then start listening, as in the example bellow:

"""python
ExternalTaskWorker(worker_id="pythonWorker", config=default_config)
    .subscribe("topic1", handle_task1)
    .subscribe("topic2", handle_task2)
    .subscribe("topic2", handle_task3)
    .start()
"""

Breaking subscription from listening not only makes code much clearer but also is a good practice if you want to handle listening in a different part of the code.
